require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PumpkinsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Pumpkin. As you add validations to Pumpkin, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PumpkinsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all pumpkins as @pumpkins" do
      pumpkin = Pumpkin.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:pumpkins)).to eq([pumpkin])
    end
  end

  describe "GET show" do
    it "assigns the requested pumpkin as @pumpkin" do
      pumpkin = Pumpkin.create! valid_attributes
      get :show, {:id => pumpkin.to_param}, valid_session
      expect(assigns(:pumpkin)).to eq(pumpkin)
    end
  end

  describe "GET new" do
    it "assigns a new pumpkin as @pumpkin" do
      get :new, {}, valid_session
      expect(assigns(:pumpkin)).to be_a_new(Pumpkin)
    end
  end

  describe "GET edit" do
    it "assigns the requested pumpkin as @pumpkin" do
      pumpkin = Pumpkin.create! valid_attributes
      get :edit, {:id => pumpkin.to_param}, valid_session
      expect(assigns(:pumpkin)).to eq(pumpkin)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pumpkin" do
        expect {
          post :create, {:pumpkin => valid_attributes}, valid_session
        }.to change(Pumpkin, :count).by(1)
      end

      it "assigns a newly created pumpkin as @pumpkin" do
        post :create, {:pumpkin => valid_attributes}, valid_session
        expect(assigns(:pumpkin)).to be_a(Pumpkin)
        expect(assigns(:pumpkin)).to be_persisted
      end

      it "redirects to the created pumpkin" do
        post :create, {:pumpkin => valid_attributes}, valid_session
        expect(response).to redirect_to(Pumpkin.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pumpkin as @pumpkin" do
        post :create, {:pumpkin => invalid_attributes}, valid_session
        expect(assigns(:pumpkin)).to be_a_new(Pumpkin)
      end

      it "re-renders the 'new' template" do
        post :create, {:pumpkin => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested pumpkin" do
        pumpkin = Pumpkin.create! valid_attributes
        put :update, {:id => pumpkin.to_param, :pumpkin => new_attributes}, valid_session
        pumpkin.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested pumpkin as @pumpkin" do
        pumpkin = Pumpkin.create! valid_attributes
        put :update, {:id => pumpkin.to_param, :pumpkin => valid_attributes}, valid_session
        expect(assigns(:pumpkin)).to eq(pumpkin)
      end

      it "redirects to the pumpkin" do
        pumpkin = Pumpkin.create! valid_attributes
        put :update, {:id => pumpkin.to_param, :pumpkin => valid_attributes}, valid_session
        expect(response).to redirect_to(pumpkin)
      end
    end

    describe "with invalid params" do
      it "assigns the pumpkin as @pumpkin" do
        pumpkin = Pumpkin.create! valid_attributes
        put :update, {:id => pumpkin.to_param, :pumpkin => invalid_attributes}, valid_session
        expect(assigns(:pumpkin)).to eq(pumpkin)
      end

      it "re-renders the 'edit' template" do
        pumpkin = Pumpkin.create! valid_attributes
        put :update, {:id => pumpkin.to_param, :pumpkin => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pumpkin" do
      pumpkin = Pumpkin.create! valid_attributes
      expect {
        delete :destroy, {:id => pumpkin.to_param}, valid_session
      }.to change(Pumpkin, :count).by(-1)
    end

    it "redirects to the pumpkins list" do
      pumpkin = Pumpkin.create! valid_attributes
      delete :destroy, {:id => pumpkin.to_param}, valid_session
      expect(response).to redirect_to(pumpkins_url)
    end
  end

end
